### PR TITLE
Packaged version

### PR DESCRIPTION
**Pull request by shepherdjay**
Packaged version for pypi

### CODE REVIEW

**Comment by shepherdjay** [comment]
@dharmab - If you have a free moment I'm not sure why it is saying no module "named" on the CI test. Works fine in pycharm but there could be some pycharm magic going on.

this is my attempt at packaging up this project for distribution

**Comment by shepherdjay** [comment]
nope travis.ci didn't like that either.

**Comment by dharmab** [comment]
Your tests are using relative imports, which require the test to be run from the correct directory. On my system `py.text --cov` only works if I'm in the `ipfromwebpage` directory. By default, Travis runs commands in the project root.

Possible solutions:
- Add a command to `travis.yml` to change directories before running tests (See https://stackoverflow.com/questions/14468464/how-to-specify-a-build-folder-in-travis)
- Put your build and test steps in a script and have the script set the directory correctly before running the tests (This is a pain if you have to support non-nix operating systems)

**Comment by dharmab** [comment]
Ah, I misled you. Should be `tests`, not `ipfromwebpage`

**Comment by dharmab** [comment]
Aha! `pytest` has weird behavior when running in a virtualenv: https://docs.pytest.org/en/latest/goodpractices.html#tox

Disregard the above directory comment, and then add `pip install -e .` to your `travis.yml` before running tests. This temporarily installs the module so that the test can import it.

**Comment by shepherdjay** [comment]
That seems to have worked. - The failure was a result of not grabbing the coverage reports which is separate issue i'll work on. Packaging is annoying.....

**Comment by shepherdjay** [comment]
It seems like the google's are mostly favoring tox instead of purely running py.test from Travis. I've never used Tox but will look into it.

**Comment by shepherdjay** [comment]
Recent commit fixed codecov ready to merge

**Pull request merged**
